
export const teacherData = [
    { id: 1, tName: 'Abdur Rahman', subject: 'Programming' },
    { id: 2, tName: 'Aisha Khan', subject: 'Mathematics' },
    { id: 3, tName: 'Bilal Ahmed', subject: 'Physics' },
    { id: 4, tName: 'Zara Sheikh', subject: 'Chemistry' },
    { id: 5, tName: 'Hamza Ali', subject: 'Biology' },
    { id: 6, tName: 'Fatima Noor', subject: 'English' },
    { id: 7, tName: 'Usman Malik', subject: 'History' },
    { id: 8, tName: 'Sara Hassan', subject: 'Geography' },
    { id: 9, tName: 'Ali Raza', subject: 'Computer Science' },
    { id: 10, tName: 'Maryam Gul', subject: 'Economics' },
    { id: 11, tName: 'Ahmed Khan', subject: 'Art' },
    { id: 12, tName: 'Nida Ahmed', subject: 'Programming' },
    { id: 13, tName: 'Hassan Tariq', subject: 'Mathematics' },
    { id: 14, tName: 'Zainab Shah', subject: 'Physics' },
    { id: 15, tName: 'Umar Iqbal', subject: 'Chemistry' },
    { id: 16, tName: 'Ayesha Karim', subject: 'Biology' },
    { id: 17, tName: 'Musa Qureshi', subject: 'English' },
    { id: 18, tName: 'Sana Rauf', subject: 'History' },
    { id: 19, tName: 'Talha Javed', subject: 'Geography' },
    { id: 20, tName: 'Rabia Hassan', subject: 'Computer Science' },
    { id: 21, tName: 'Ibrahim Khan', subject: 'Economics' },
    { id: 22, tName: 'Sadia Munir', subject: 'Art' },
    { id: 23, tName: 'Kamran Ali', subject: 'Programming' },
    { id: 24, tName: 'Mariam Saeed', subject: 'Mathematics' },
    { id: 25, tName: 'Danish Farooq', subject: 'Physics' },
    { id: 26, tName: 'Farah Ahmed', subject: 'Chemistry' },
    { id: 27, tName: 'Zohaib Khan', subject: 'Biology' },
    { id: 28, tName: 'Laila Tariq', subject: 'English' },
    { id: 29, tName: 'Yasir Mehmood', subject: 'History' },
    { id: 30, tName: 'Anam Malik', subject: 'Geography' },
    { id: 31, tName: 'Hiba Jamil', subject: 'Computer Science' },
    { id: 32, tName: 'Shahid Ali', subject: 'Economics' },
    { id: 33, tName: 'Erum Waqar', subject: 'Art' },
    { id: 34, tName: 'Noman Khalid', subject: 'Programming' },
    { id: 35, tName: 'Hira Shahid', subject: 'Mathematics' },
    { id: 36, tName: 'Junaid Iqbal', subject: 'Physics' },
    { id: 37, tName: 'Maliha Khan', subject: 'Chemistry' },
    { id: 38, tName: 'Tariq Latif', subject: 'Biology' },
    { id: 39, tName: 'Saba Qureshi', subject: 'English' },
    { id: 40, tName: 'Kashif Ahmed', subject: 'History' },
]