
export const menuData = [
    {
        id: 1,
        foodType: "Lunch",
        description: "Beef Steak with Fried Potato",
        rating: "4.9",
        order: "1,496",
        interest: "26%",
      },
      {
        id: 2,
        foodType: "Breakfast",
        description: "Avocado Toast with Eggs",
        rating: "4.8",
        order: "1,250",
        interest: "30%",
      },
      {
        id: 3,
        foodType: "Snack",
        description: "Cheese Nachos with Salsa",
        rating: "4.5",
        order: "980",
        interest: "18%",
      },
      {
        id: 4,
        foodType: "Lunch",
        description: "Grilled Salmon and Veggies",
        rating: "4.7",
        order: "1,350",
        interest: "22%",
      },
      {
        id: 5,
        foodType: "Breakfast",
        description: "Banana Smoothie Bowl",
        rating: "4.6",
        order: "1,100",
        interest: "28%",
      },
      {
        id: 6,
        foodType: "Snack",
        description: "Chocolate Chip Cookies",
        rating: "4.4",
        order: "850",
        interest: "16%",
      },
      {
        id: 7,
        foodType: "Lunch",
        description: "Chicken Alfredo Pasta",
        rating: "4.8",
        order: "1,600",
        interest: "35%",
      },
      {
        id: 8,
        foodType: "Breakfast",
        description: "Blueberry Muffins",
        rating: "4.3",
        order: "900",
        interest: "20%",
      },
      {
        id: 9,
        foodType: "Snack",
        description: "Veggie Spring Rolls",
        rating: "4.1",
        order: "750",
        interest: "12%",
      },
      {
        id: 10,
        foodType: "Lunch",
        description: "BBQ Ribs with Coleslaw",
        rating: "4.9",
        order: "1,800",
        interest: "38%",
      },
      {
        id: 11,
        foodType: "Breakfast",
        description: "Oatmeal with Fresh Fruits",
        rating: "4.5",
        order: "1,050",
        interest: "25%",
      },
      {
        id: 12,
        foodType: "Snack",
        description: "Popcorn with Butter",
        rating: "4.0",
        order: "600",
        interest: "10%",
      },
      {
        id: 13,
        foodType: "Lunch",
        description: "Vegetarian Burrito Bowl",
        rating: "4.7",
        order: "1,300",
        interest: "27%",
      },
      {
        id: 14,
        foodType: "Breakfast",
        description: "Egg Benedict with Sauce",
        rating: "4.6",
        order: "1,200",
        interest: "32%",
      },
      {
        id: 15,
        foodType: "Snack",
        description: "Mixed Nuts and Seeds",
        rating: "4.2",
        order: "700",
        interest: "14%",
      },
      {
        id: 16,
        foodType: "Lunch",
        description: "Shrimp Fried Rice",
        rating: "4.8",
        order: "1,450",
        interest: "33%",
      },
      {
        id: 17,
        foodType: "Breakfast",
        description: "French Toast with Syrup",
        rating: "4.4",
        order: "950",
        interest: "19%",
      },
      {
        id: 18,
        foodType: "Snack",
        description: "Fruit Salad with Yogurt",
        rating: "4.3",
        order: "820",
        interest: "22%",
      },
      {
        id: 19,
        foodType: "Lunch",
        description: "Turkey Club Sandwich",
        rating: "4.5",
        order: "1,300",
        interest: "24%",
      },
      {
        id: 20,
        foodType: "Breakfast",
        description: "Bagel with Cream Cheese",
        rating: "4.1",
        order: "700",
        interest: "15%",
      },
      {
        id: 21,
        foodType: "Snack",
        description: "Pretzels with Mustard",
        rating: "4.0",
        order: "680",
        interest: "13%",
      },
]